version: 0.2
phases:
    pre_build:
        commands:
            - nodejs -v
            - npm install
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build