version: 0.2
phases:
    pre_build:
        commands:
            - echo install nodejs
            - apt install -y nodejs
            - echo Verify Install
            - nodejs -v
            - echo Install NPM
            - apt install -y npm
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build