version: 0.2
phases:
    pre_build:
        commands:
            - echo install nodejs
            - apt update
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build