version: 0.2
phases:
    pre_build:
        commands:
            - echo Upgrade the System
            - apt update
            - echo Install NodeJs
            - apt install nodejs -y
            - echo Verify Install
            - nodejs -v
            - echo Install NPM
            - apt install npm -y
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build