version: 0.2
phases:
    pre_build:
        commands:
            - echo Install NodeJs
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            - . ~/.nvm/nvm.sh
            - echo Install NodeJs
            - nvm install node
            - echo Checking Version
            - node -v 
            - echo Install NPM
            - npm install
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build