version: 0.2
phases:
    install:
      runtime-versions:
        nodejs: 10.19.0
        npm: 6.14.4

    pre_build:
        commands:
            - echo PreBuild
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build