version: 0.2
phases:
    pre_build:
        commands:
            - echo install nodejs
            - nodejs install
            - echo Verify Install
            - nodejs -v
            - echo Install NPM
            - npm install
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build