version: 0.2
phases:
    install:
      runtime-versions:
        nodejs: 10

    pre_build:
        commands:
            - echo install npm
            - npm install
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: build