version: 0.2
phases:
    pre_build:
        commands:
            - echo Install NodeJs
            - node -v 
            - echo Install NPM
            - npm install
    build:
        commands:
            - npm run build
artifacts:
    files:
        - '**/*'
    discard-paths: no
    build-directory: ~/node_modules